namespace SharpIDE
{
    public enum CPPScintillaID {
        DEFAULT,COMMENT,COMMENT_INLINE,COMMENTDOC,NUMBER,WORD,STRING,CHAR,UUID,PREPROCESSOR,OPERATOR,ID,STRINGEOL,VERBATIM,REGEX,COMMENTLINEDOC,WORD2,COMMENTDOCKEYWORD,COMMENTDOCKEYWORDERROR,GLOBALCLASS,STRINGRAW,TRIPLIVERBATIM,HASHQUOTEDSTRING,PREPROCESSORCOMMENT,PREPROCESSORCOMMENTDOC,USERLITERAL,TASKMARKER,ESCAPESEQEUENCE
        
    }
}